/**
 * @file ecu_dash2.c
 *
 * @brief This source file was generated by cantools version 40.2.2 Sat Jun 14 01:20:09 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "ecu_dash2.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int ecu_dash2_motor_status_pack(
    uint8_t *dst_p,
    const struct ecu_dash2_motor_status_t *src_p,
    size_t size)
{
    uint16_t inv_dc_bus_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u16(src_p->inv_fast_dc_bus_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->inv_fast_dc_bus_voltage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->inv_fast_motor_speed, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->inv_fast_motor_speed, 8u, 0xffu);
    inv_dc_bus_current = (uint16_t)src_p->inv_dc_bus_current;
    dst_p[5] |= pack_left_shift_u16(inv_dc_bus_current, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(inv_dc_bus_current, 8u, 0xffu);

    return (8);
}

int ecu_dash2_motor_status_unpack(
    struct ecu_dash2_motor_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t inv_dc_bus_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inv_fast_dc_bus_voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->inv_fast_dc_bus_voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->inv_fast_motor_speed = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->inv_fast_motor_speed |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    inv_dc_bus_current = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    inv_dc_bus_current |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->inv_dc_bus_current = (int16_t)inv_dc_bus_current;

    return (0);
}

int ecu_dash2_motor_status_init(struct ecu_dash2_motor_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ecu_dash2_motor_status_t));

    return 0;
}

uint16_t ecu_dash2_motor_status_inv_fast_dc_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double ecu_dash2_motor_status_inv_fast_dc_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool ecu_dash2_motor_status_inv_fast_dc_bus_voltage_is_in_range(uint16_t value)
{
    return (value <= 3277u);
}

uint16_t ecu_dash2_motor_status_inv_fast_motor_speed_encode(double value)
{
    return (uint16_t)(value);
}

double ecu_dash2_motor_status_inv_fast_motor_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool ecu_dash2_motor_status_inv_fast_motor_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ecu_dash2_motor_status_inv_dc_bus_current_encode(double value)
{
    return (int16_t)(value);
}

double ecu_dash2_motor_status_inv_dc_bus_current_decode(int16_t value)
{
    return ((double)value);
}

bool ecu_dash2_motor_status_inv_dc_bus_current_is_in_range(int16_t value)
{
    return ((value >= -3277) && (value <= 3277));
}

int ecu_dash2_fault_status_pack(
    uint8_t *dst_p,
    const struct ecu_dash2_fault_status_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->imd_fault, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->bmsc_fault, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->apps_fault, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->bppc_fault, 3u, 0x08u);

    return (1);
}

int ecu_dash2_fault_status_unpack(
    struct ecu_dash2_fault_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->imd_fault = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->bmsc_fault = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->apps_fault = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->bppc_fault = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    return (0);
}

int ecu_dash2_fault_status_init(struct ecu_dash2_fault_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ecu_dash2_fault_status_t));

    return 0;
}

uint8_t ecu_dash2_fault_status_imd_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_fault_status_imd_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_fault_status_imd_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_fault_status_bmsc_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_fault_status_bmsc_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_fault_status_bmsc_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_fault_status_apps_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_fault_status_apps_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_fault_status_apps_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_fault_status_bppc_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_fault_status_bppc_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_fault_status_bppc_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ecu_dash2_car_status_pack(
    uint8_t *dst_p,
    const struct ecu_dash2_car_status_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rtd, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ir_plus_signal, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->limp_mode, 2u, 0x04u);

    return (1);
}

int ecu_dash2_car_status_unpack(
    struct ecu_dash2_car_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rtd = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ir_plus_signal = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->limp_mode = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    return (0);
}

int ecu_dash2_car_status_init(struct ecu_dash2_car_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ecu_dash2_car_status_t));

    return 0;
}

uint8_t ecu_dash2_car_status_rtd_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_car_status_rtd_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_car_status_rtd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_car_status_ir_plus_signal_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_car_status_ir_plus_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_car_status_ir_plus_signal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_car_status_limp_mode_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_car_status_limp_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_car_status_limp_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ecu_dash2_bms_info_pack(
    uint8_t *dst_p,
    const struct ecu_dash2_bms_info_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->battery_percentage, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->total_pack_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->total_pack_voltage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->highest_temperature, 0u, 0xffu);

    return (4);
}

int ecu_dash2_bms_info_unpack(
    struct ecu_dash2_bms_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->battery_percentage = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->total_pack_voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->total_pack_voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->highest_temperature = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int ecu_dash2_bms_info_init(struct ecu_dash2_bms_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ecu_dash2_bms_info_t));

    return 0;
}

uint8_t ecu_dash2_bms_info_battery_percentage_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_bms_info_battery_percentage_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_bms_info_battery_percentage_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint16_t ecu_dash2_bms_info_total_pack_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double ecu_dash2_bms_info_total_pack_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool ecu_dash2_bms_info_total_pack_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint8_t ecu_dash2_bms_info_highest_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_bms_info_highest_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_bms_info_highest_temperature_is_in_range(uint8_t value)
{
    return (value <= 150u);
}

int ecu_dash2_cooling_pack(
    uint8_t *dst_p,
    const struct ecu_dash2_cooling_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->cooling_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->too_hot, 1u, 0x02u);

    return (1);
}

int ecu_dash2_cooling_unpack(
    struct ecu_dash2_cooling_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->cooling_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->too_hot = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    return (0);
}

int ecu_dash2_cooling_init(struct ecu_dash2_cooling_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ecu_dash2_cooling_t));

    return 0;
}

uint8_t ecu_dash2_cooling_cooling_on_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_cooling_cooling_on_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_cooling_cooling_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ecu_dash2_cooling_too_hot_encode(double value)
{
    return (uint8_t)(value);
}

double ecu_dash2_cooling_too_hot_decode(uint8_t value)
{
    return ((double)value);
}

bool ecu_dash2_cooling_too_hot_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
